### ISSUE TITLE
Missing Solarium\Client class throws a PHP Fatal Error

### ISSUE THREAD

**Issue by anavarre** [amateescu/search_api_solr#41]
Tried to click around with Search API and the Acquia Search backend and noticed a PHP Fatal when trying to display <strong>admin/config/search/search-api/index/acquia_search_index</strong> - This comes from the below error:

```
[Fri Feb 13 10:50:31.364771 2015] [:error] [pid 10687] [client 127.0.0.1:40463] 
PHP Fatal error:  Class 'Solarium\\Client' not found in
/html/d8/modules/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php
on line 922, referer: http://d8/admin/config/search/search-api/index/acquia_search_index/edit
```

Looked into the codebase and <strong>SearchApiSolrBackend.php</strong> seems to have many missing bits yet, and especially that Solarium client.

**Comment by Berdir** [comment]
You need to get that using composer, either with composer_manager.module or by calling composer install within the module directory.

**Comment by anavarre** [comment]
Oh, ok. My bad. I suggest adding that to the README.txt file, then as I didn't notice it shipped with its own composer.json file.

Filed #42
