### ISSUE TITLE
Fatal error: Call to undefined method Drupal\search_api\Utility::getDataTypeInfo() in search_api_solr/src/Utility/Utility.php on line 50

### ISSUE THREAD

**Issue by ismaeil** [amateescu/search_api_solr#58]
Hi,
With last codebase of search_api, defining an index of solr server (admin/config/search/search-api/add-index) would throw 
Fatal error: Call to undefined method Drupal\search_api\Utility::getDataTypeInfo() in search_api_solr/src/Utility/Utility.php on line 50

**Comment by ismaeil** [comment]
actually, it shoudl just be replaced with the new method from search_api : getDefaultDataTypes()

**Comment by Berdir** [comment]
That's not the same method, this method is now on the data type service and called getDataTypeDefinitions()
