### ISSUE TITLE
Special characters like Backspace in content are not accepted by solr

### ISSUE THREAD

**Issue by Berdir** [amateescu/search_api_solr#66]
We had an Error 400 Illegal character ((CTRL-CHAR, code 8)) exception when indexing content on one site.

After quite a bit of debugging, I found the node that was causing it and I also managed, after many wrong tries, to configure the ignore characters search api filter to exclude \x08.

It seems that either solarium or search_api_solr should always drop characters that solr will not accept to avoid errors like that. It could log a warning message or so?

**Comment by mkalkbrenner** [comment]
In apachesolr 7.x we had a filter for that. The equivalent here seems to be Solarium\Core\Query\Helper::filterControlCharacters().
So we should create a patch for Solarium.
