### ISSUE TITLE
Amazon Cloudsearch compatibility

### ISSUE THREAD

**Issue by ivanjaros** [amateescu/search_api_solr#72]
Hi,
will Drupal 8 version be compatible/usable with Amazon's Cloudsearch, which is basically Apache SOLR?

**Comment by drunken-monkey** [comment]
Unless I'm mistaken, ACS, while basically just Solr, uses a completely different structure for both their indexing and search requests, so it would be almost impossible to make the code work with both ACS and normal Solr.
So, in a nutshell: no.

**Comment by ivanjaros** [comment]
Ok ,thanks for the info.
