### ISSUE TITLE
Read this! Moved this project to search_api_solr

### ISSUE THREAD

**Issue by nickveenhof** [amateescu/search_api_solr#76]
Hi all,

together with @mkalkbrenner , @drunken-monkey, @amateescu  and myself we had a discussion that it was in the importance of this project that it moves to drupal.org. @drunken-monkey gave all of us commit access to search_api_solr but only for the 8.x branch. 

The 8.x-1.x branch will be pushed to github on a 10 minute interval so development can continue here, but all individual commits to 8.x-1.x will be removed in github due to this workflow.

Project can be found here: https://www.drupal.org/project/search_api_solr

**Comment by nickveenhof** [comment]
To start I pushed the code to the 8.x-1.x branch in search_api_solr but we need some follow-up steps so we can get this working.

1. We need a deployment key, @amateescu you are our best chance here as you own this repository. Please pm me the key and I can set up jenkins.
2. We need to update the documentation to reflect this change.

**Comment by amateescu** [comment]
I did the deployment key stuff, it should be in your inbox :)

**Comment by nickveenhof** [comment]
Jenkins was configured and it is pushing every 15 minutes! We also need to close the issue queue here and tell people to create issues in drupal.org?

**Comment by drunken-monkey** [comment]
I now also changed the d.o project page to reflect this change and
created a dev snapshot release?
Do you want to also create an initial Alpha release right away? You have
all the necessary permissions, if you want to.

**Comment by nickveenhof** [comment]
Might not be that bad indeed. Most things are working so I'll go ahead and do that.

**Comment by MPParsley** [comment]
@amateescu perhaps you can close this issue or add a link to 
https://github.com/mkalkbrenner/search_api_solr/blob/8.x-2.x/README.md

**Comment by amateescu** [comment]
Sure, let's close it since it's no longer relevant :)
